#!/usr/bin/zsh
# This hook is sourced after every virtualenv is activated.
#

RPROMPT='`basename $VIRTUAL_ENV`'
#!/usr/bin/zsh
# This hook is sourced after every virtualenv is activated.
#

CURRENT_BG='NONE'
RIGHT_SEGMENT_SEPARATOR=$'\uE0B2' 

rprompt_segment (){
	local bg fg
	[[ -n $1 ]] && bg="%K{$1}" || bg="%k"
	[[ -n $2 ]] && fg="%F{$2}" || fg="%f"
	CURRENT_BG=$1
	echo -n "  %{$fg%F{$CURRENT_BG}%}$RIGHT_SEGMENT_SEPARATOR%{$bg%F{$CURRENT_BG}%}%{$fg%} "
	[[ -n $2 ]] && echo -n $3
}

rprompt_end() {
	if [[ -n $CURRENT_BG ]]; then                                           
		echo -n " $RIGHT_SEGMENT_SEPARATOR%{%k%F{$CURRENT_BG}%}"              
	else
		echo -n "%{%k%}"
	fi
	echo -n "%{%f%}"
	CURRENT_BG=''
}    

rprompt_venvs(){
	local virtualenv_path="$VIRTUAL_ENV"                                    
	if [[ -n $virtualenv_path && -n $VIRTUAL_ENV_DISABLE_PROMPT ]]; then    
		rprompt_segment white black "\u2699 `basename $virtualenv_path`"
	fi
}

build(){
	RETVAL=$?
	rprompt_venvs
	rprompt_end
}

RPROMPT="%{%f%b%k%}$(build)"
